### ISSUE TITLE
Respect Keyword Mutes from Website

### ISSUE THREAD

**Issue by scottiefalkon** [tooot-app/app#487]
I've noticed other apps respect the keyword mutes you have setup on the Mastodon web interface. That would be very nice to have.

**Comment by xmflsct** [comment]
Do you mean filters? If so, it should work. If not, please share the set up that does not work so I can investigate.

**Comment by joerghohn** [comment]
It does not work,
for example, I have a filter for twitter shit (twitter, #twitter, @RT and some more). Another filter for some soccer content, including the local team SV98 (Darmstad
In tooot-app all toots are shown directly, no filter is working.

**Comment by scottiefalkon** [comment]
"RT @" and "RT" are not working. The others sre.

**Comment by joerghohn** [comment]
None is working for me. All tooots with filtered words are shown directly

**Comment by xmflsct** [comment]
Likely had been fixed in https://github.com/tooot-app/app/issues/530 but not yet released. @joerghohn can you help me confirm the ones that are not working at the moment have "whole word" checked in the web UI?

**Comment by joerghohn** [comment]
Yes, whole word is checked

<img width="864" alt="image" src="https://user-images.githubusercontent.com/22028904/206501662-40cb95b1-20dd-4c32-8e48-acabf7ba6d9e.png">

**Comment by joerghohn** [comment]
Thank you, I will have a look on it.

**Comment by xmflsct** [comment]
It should have been fixed in v4.7.0. But in the upcoming v4.7.1, filter logic will be using the one supplied by the server side (introduced in Mastodon since v4) https://github.com/tooot-app/app/issues/572.

**Comment by joerghohn** [comment]
Nope, 
toots with the word Twitter are still shown directly. Filter is as in the attached screenshot.
![88125975-537C-4520-8222-20121A4F901F](https://user-images.githubusercontent.com/22028904/208320244-f2adae71-818c-4034-8227-65764f22e9d4.jpeg)

**Comment by xmflsct** [comment]
Thanks @joerghohn. Will get the v4.7.1 out in few days.

**Comment by joerghohn** [comment]
Seems that, also i did an update, the old version was still running. After phone reboot it works now. I can‘t see any unfiltered toots with „filter-words“ now.

Thank you
